### ISSUE TITLE
Called Tesseract does not read the environment variable TESSDATA_PREFIX

### ISSUE THREAD

**Issue by treylav** [intra2net/guibot#29]
I'm trying to run example code from the [documentation](https://guibot.readthedocs.io/en/latest/README.html):
```python
from guibot.region import Region
from guibot.fileresolver import FileResolver
from guibot.target import Image, Text
from guibot.finder import TextFinder

# add the paths to all target files through a more general file resolver
file_resolver = FileResolver()
file_resolver.add_path('target_data/')

# define more general targets like image instance (default from string before)
# and a text target to read out from the screen
some_image = Image('shape_blue_circle')
some_text = Text('Some text here')

# define a region instead of the previous guibot object capable of the same
# calls with the exception of path handling from the file resolver
image_region = Region()
# define a region with a different CV backend, namely a text finder with its
# default OCR backends (also can be found in the config module)
text_region = Region(cv=TextFinder())
# click on the image instance using all default settings and wait for it to vanish
image_region.click_vanish(some_image)
# hover the mouse on top of the text that was read from the screen but
# reusing the matched subregion
read_text = text_region.hover(some_text)
```
As a result, I get an error:
```
Traceback (most recent call last):
  File "C:\project\__init__.py", line 33, in <module>
    read_text = text_region.hover(some_text)
  File "C:\project\venv\lib\site-packages\guibot\region.py", line 641, in hover
    match = self.find(target_or_location)
  File "C:\project\venv\lib\site-packages\guibot\region.py", line 406, in find
    found_pics = cv_backend.find(target, screen_capture)
  File "C:\project\venv\lib\site-packages\guibot\finder.py", line 2169, in find
    output = self.ocr.image_to_string(text_img,
  File "C:\project\venv\lib\site-packages\pytesseract\pytesseract.py", line 413, in image_to_string
    return {
  File "C:\project\venv\lib\site-packages\pytesseract\pytesseract.py", line 416, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\project\venv\lib\site-packages\pytesseract\pytesseract.py", line 284, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\project\venv\lib\site-packages\pytesseract\pytesseract.py", line 260, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file ../misctessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

Process finished with exit code 1
```
As a separate module, ``pytesseract`` works as expected in same virtual environment, I used [example code from project page](https://github.com/madmaze/pytesseract/blob/master/README.rst). As standalone console application tesseract works too.

Environment variables set correctly:
```python
>> import os
>> os.environ['PATH']
<...>
C:\\Program Files\\Tesseract-OCR
>> os.environ['TESSDATA_PREFIX']
C:\\Program Files\\Tesseract-OCR\\tessdata
``` 

``tessdata`` files for English is installed:
```
>dir "C:\Program Files\Tesseract-OCR\tessdata"

 Directory of C:\Program Files\Tesseract-OCR\tessdata

16.07.2021  17:57    <DIR>          .
16.07.2021  17:57    <DIR>          ..
16.07.2021  17:57    <DIR>          configs
06.05.2021  13:11         4 113 088 eng.traineddata
16.01.2019  23:53                33 eng.user-patterns
16.01.2019  23:53                27 eng.user-words
06.05.2021  14:44           128 076 jaxb-api-2.3.1.jar
06.05.2021  13:11        10 562 727 osd.traineddata
06.05.2021  15:07               572 pdf.ttf
06.05.2021  14:44           125 187 piccolo2d-core-3.0.1.jar
06.05.2021  14:44           149 558 piccolo2d-extras-3.0.1.jar
16.07.2021  17:57    <DIR>          script
06.05.2021  14:44            26 078 ScrollView.jar
16.07.2021  17:57    <DIR>          tessconfigs
               9 File(s)     15 105 346 bytes
               5 Dir(s)  12 203 257 856 bytes free
```

- Microsoft Windows 10 Professional N (x64) Build 19043.1052
- Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
- tesseract v5.0.0-alpha.20210506
- pytesseract 0.3.8
- guibot 0.41.1

Thanks in advance for help.

**Comment by linkyeu** [comment]
How it was fixed?

**Comment by pevogam** [comment]
@linkyeu I think @treylav could tell you more since he closed the issue on the same day but essentially the tessdata files are only included in the git repository but not in the PyPI package so you will have to place them in the correct location yourself. I then commented in https://github.com/intra2net/guibot/issues/27#issuecomment-881736312 and I think this was sufficient to resolve any leftover problems.
